### ISSUE TITLE
Status method missing?

### ISSUE THREAD

**Issue by af-multichannelsystems** [Inateck-Technology-Inc/csharp_sdk#2]
Hallo,

is the method "inateck_scanner_ble_auth" the correct way to determine if a scanner is currently connected?
Or will it do something I'm not accounting for? If yes, a status method would be great.

**Comment by soSeven** [comment]
The "inateck_scanner_ble_auth" method is utilized for authenticating the barcode scanner in GATT mode, irrespective of its connection status. In HID mode, this method invocation is optional and may be omitted.
