### ISSUE TITLE
Debug mode only working with console?

### ISSUE THREAD

**Issue by af-multichannelsystems** [Inateck-Technology-Inc/csharp_sdk#3]
Hello there,

as the application I'm using is running with Windows Forms, the debug mode doesn't provide a possibility to print output to.

Would it be possible to redirect the output using a callback or something similar?

**Comment by soSeven** [comment]
At present, this feature is not supported; however, we will certainly consider adding it to our future update plans. We appreciate your patience and look forward to enhancing your experience with this addition.
