### ISSUE TITLE
Disconnecting sends reply out before actually disconnecting

### ISSUE THREAD

**Issue by af-multichannelsystems** [Inateck-Technology-Inc/csharp_sdk#4]
When using the demo program and typing !disconnect, the message, that the scanner has been disconnected occurs before the scanner vibrates (signaling the disconnect). This makes reconnecting a bit annoying as I have to implement a timer with an estimate of 3s to enable reconnecting. If you try connecting in the timespan from sending out the command and it actually disconnecting, connecting fails.

Is there an easy way to fix that?

![ScannerException](https://github.com/user-attachments/assets/399d3e7f-ea19-48af-8fa2-4afc41d73fe2)

**Comment by soSeven** [comment]
Indeed, this issue currently exists. A viable workaround is to disconnect from the device, then rescan for available devices in your vicinity, and attempt to reconnect. This process can help circumvent the problem at hand. Rest assured, we are diligently working on rectifying this glitch and are committed to delivering an improved solution that will enhance your experience.

**Comment by af-multichannelsystems** [comment]
Perfect. Thanks a lot!
Please let me know as soon as the new version is available.
